server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rabbit_blog?serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKeyId: LTAI5tJGwmuMbwQoq1tkoRaj
  accessKeySecret: eHtirKJzb9r6DVtS7hvyESD22Vh1uf
  bucketName: watermelonetwork
  endpoint: oss-cn-zhangjiakou.aliyuncs.com